---
  version: "3"
  services:
    autoreply:
      image: praul1/autoreply:latest
      container_name: autoreply_autoreply
      environment:
        - PUID=1000
        - PGID=100
      # - TZ=Europe/Amsterdam
      volumes:
        - ./repliers.py:/app/repliers.py #you need to customize the repliers.py file and change path accordingy
        - ./db:/app/db #this can be an empty, writable folder
        - /etc/localtime:/etc/localtime:ro #for correct timezone. Leave as is
   
      restart: unless-stopped
      logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "2m"
    
    dozzle:
      container_name: autoreply_dozzle #this is for monitoring autoreply log in webbrowser. not needed
      image: amir20/dozzle:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 10101:8080
      command: --filter name=autoreply_autoreply
      restart: unless-stopped
  
